name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода и установка зависимостей
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u astaeas --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # Сборка и публикация Docker образа для бэкенда
      - name: Build and push backend Docker image
        run: |
          docker build -t astaeas/myapp-backend:${{ github.sha }} -f backend/Dockerfile ./backend
          docker tag astaeas/myapp-backend:${{ github.sha }} docker.io/astaeas/myapp-backend:latest
          docker push docker.io/astaeas/myapp-backend:${{ github.sha }}
          docker push docker.io/astaeas/myapp-backend:latest
      # Сборка и публикация Docker образа для фронтенда
      - name: Build and push frontend Docker image
        run: |
          docker build -t astaeas/myapp-frontend:${{ github.sha }} -f frontend/Dockerfile ./frontend
          docker tag astaeas/myapp-frontend:${{ github.sha }} docker.io/astaeas/myapp-frontend:latest
          docker push docker.io/astaeas/myapp-frontend:${{ github.sha }}
          docker push docker.io/astaeas/myapp-frontend:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          docker-compose pull  # тянет последние версии образов
          docker-compose up -d  # поднимает все сервисы в фоне
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
